version: '3.8'

services:

  app:
    image: reserva:latest
    container_name: reserva
    build:
      context: .
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: