spring:
  profiles:
    active: local
  application:
    name: '@project.name@'
  data:
    mongodb:
#      uri: mongodb://localhost/reserva
     uri: mongodb://${db.username}:${db.password}@${db.host}:${db.port}/${db.database}?authSource=admin
#      host: ${MONGO_HOST}
#      port: ${MONGO_PORT}
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    br.com.grupo27: DEBUG
