#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: admin
#      password: admin
server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    br.com.grupo27: DEBUG
db:
    host: localhost
    port: 27017
    database: reserva
    username: admin
    password: admin