spring:
  application:
    name: '@project.name@'
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/reserva?authSource=admin&retryWrites=false
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    br.com.grupo27: DEBUG