spring:
  application:
    name: '@project.name@'
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/reserva?authSource=admin

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    br.com.grupo27: DEBUG