spring:
  data:
    mongodb:
      uri: mongodb://localhost/reserva
    #  uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE}?retryWrites=true&w=majority&appName=postech-reserva